// Code generated by entc, DO NOT EDIT.

package ent

import (
	"oauth-az/ent/authcode"
	"oauth-az/ent/authrequest"
	"oauth-az/ent/oauth2client"
	"oauth-az/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authcodeMixin := schema.AuthCode{}.Mixin()
	authcodeMixinFields0 := authcodeMixin[0].Fields()
	_ = authcodeMixinFields0
	authcodeMixinFields1 := authcodeMixin[1].Fields()
	_ = authcodeMixinFields1
	authcodeFields := schema.AuthCode{}.Fields()
	_ = authcodeFields
	// authcodeDescCreatedAt is the schema descriptor for created_at field.
	authcodeDescCreatedAt := authcodeMixinFields0[0].Descriptor()
	// authcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	authcode.DefaultCreatedAt = authcodeDescCreatedAt.Default.(func() time.Time)
	// authcodeDescUpdatedAt is the schema descriptor for updated_at field.
	authcodeDescUpdatedAt := authcodeMixinFields0[1].Descriptor()
	// authcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authcode.DefaultUpdatedAt = authcodeDescUpdatedAt.Default.(func() time.Time)
	// authcodeDescCreateTime is the schema descriptor for create_time field.
	authcodeDescCreateTime := authcodeMixinFields1[0].Descriptor()
	// authcode.DefaultCreateTime holds the default value on creation for the create_time field.
	authcode.DefaultCreateTime = authcodeDescCreateTime.Default.(func() time.Time)
	// authcodeDescUpdateTime is the schema descriptor for update_time field.
	authcodeDescUpdateTime := authcodeMixinFields1[1].Descriptor()
	// authcode.DefaultUpdateTime holds the default value on creation for the update_time field.
	authcode.DefaultUpdateTime = authcodeDescUpdateTime.Default.(func() time.Time)
	// authcode.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	authcode.UpdateDefaultUpdateTime = authcodeDescUpdateTime.UpdateDefault.(func() time.Time)
	// authcodeDescValue is the schema descriptor for value field.
	authcodeDescValue := authcodeFields[0].Descriptor()
	// authcode.DefaultValue holds the default value on creation for the value field.
	authcode.DefaultValue = authcodeDescValue.Default.(func() uuid.UUID)
	// authcodeDescClientID is the schema descriptor for client_id field.
	authcodeDescClientID := authcodeFields[1].Descriptor()
	// authcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	authcode.ClientIDValidator = authcodeDescClientID.Validators[0].(func(string) error)
	// authcodeDescNonce is the schema descriptor for nonce field.
	authcodeDescNonce := authcodeFields[4].Descriptor()
	// authcode.NonceValidator is a validator for the "nonce" field. It is called by the builders before save.
	authcode.NonceValidator = authcodeDescNonce.Validators[0].(func(string) error)
	// authcodeDescRedirectURI is the schema descriptor for redirect_uri field.
	authcodeDescRedirectURI := authcodeFields[5].Descriptor()
	// authcode.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	authcode.RedirectURIValidator = authcodeDescRedirectURI.Validators[0].(func(string) error)
	// authcodeDescCodeChallenge is the schema descriptor for code_challenge field.
	authcodeDescCodeChallenge := authcodeFields[7].Descriptor()
	// authcode.DefaultCodeChallenge holds the default value on creation for the code_challenge field.
	authcode.DefaultCodeChallenge = authcodeDescCodeChallenge.Default.(string)
	authrequestMixin := schema.AuthRequest{}.Mixin()
	authrequestMixinFields0 := authrequestMixin[0].Fields()
	_ = authrequestMixinFields0
	authrequestMixinFields1 := authrequestMixin[1].Fields()
	_ = authrequestMixinFields1
	authrequestFields := schema.AuthRequest{}.Fields()
	_ = authrequestFields
	// authrequestDescCreatedAt is the schema descriptor for created_at field.
	authrequestDescCreatedAt := authrequestMixinFields0[0].Descriptor()
	// authrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	authrequest.DefaultCreatedAt = authrequestDescCreatedAt.Default.(func() time.Time)
	// authrequestDescUpdatedAt is the schema descriptor for updated_at field.
	authrequestDescUpdatedAt := authrequestMixinFields0[1].Descriptor()
	// authrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authrequest.DefaultUpdatedAt = authrequestDescUpdatedAt.Default.(func() time.Time)
	// authrequestDescCreateTime is the schema descriptor for create_time field.
	authrequestDescCreateTime := authrequestMixinFields1[0].Descriptor()
	// authrequest.DefaultCreateTime holds the default value on creation for the create_time field.
	authrequest.DefaultCreateTime = authrequestDescCreateTime.Default.(func() time.Time)
	// authrequestDescUpdateTime is the schema descriptor for update_time field.
	authrequestDescUpdateTime := authrequestMixinFields1[1].Descriptor()
	// authrequest.DefaultUpdateTime holds the default value on creation for the update_time field.
	authrequest.DefaultUpdateTime = authrequestDescUpdateTime.Default.(func() time.Time)
	// authrequest.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	authrequest.UpdateDefaultUpdateTime = authrequestDescUpdateTime.UpdateDefault.(func() time.Time)
	// authrequestDescRequestID is the schema descriptor for request_id field.
	authrequestDescRequestID := authrequestFields[0].Descriptor()
	// authrequest.DefaultRequestID holds the default value on creation for the request_id field.
	authrequest.DefaultRequestID = authrequestDescRequestID.Default.(func() uuid.UUID)
	// authrequestDescCodeChallenge is the schema descriptor for code_challenge field.
	authrequestDescCodeChallenge := authrequestFields[9].Descriptor()
	// authrequest.DefaultCodeChallenge holds the default value on creation for the code_challenge field.
	authrequest.DefaultCodeChallenge = authrequestDescCodeChallenge.Default.(string)
	oauth2clientMixin := schema.OAuth2Client{}.Mixin()
	oauth2clientMixinFields0 := oauth2clientMixin[0].Fields()
	_ = oauth2clientMixinFields0
	oauth2clientMixinFields1 := oauth2clientMixin[1].Fields()
	_ = oauth2clientMixinFields1
	oauth2clientFields := schema.OAuth2Client{}.Fields()
	_ = oauth2clientFields
	// oauth2clientDescCreatedAt is the schema descriptor for created_at field.
	oauth2clientDescCreatedAt := oauth2clientMixinFields0[0].Descriptor()
	// oauth2client.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauth2client.DefaultCreatedAt = oauth2clientDescCreatedAt.Default.(func() time.Time)
	// oauth2clientDescUpdatedAt is the schema descriptor for updated_at field.
	oauth2clientDescUpdatedAt := oauth2clientMixinFields0[1].Descriptor()
	// oauth2client.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauth2client.DefaultUpdatedAt = oauth2clientDescUpdatedAt.Default.(func() time.Time)
	// oauth2clientDescCreateTime is the schema descriptor for create_time field.
	oauth2clientDescCreateTime := oauth2clientMixinFields1[0].Descriptor()
	// oauth2client.DefaultCreateTime holds the default value on creation for the create_time field.
	oauth2client.DefaultCreateTime = oauth2clientDescCreateTime.Default.(func() time.Time)
	// oauth2clientDescUpdateTime is the schema descriptor for update_time field.
	oauth2clientDescUpdateTime := oauth2clientMixinFields1[1].Descriptor()
	// oauth2client.DefaultUpdateTime holds the default value on creation for the update_time field.
	oauth2client.DefaultUpdateTime = oauth2clientDescUpdateTime.Default.(func() time.Time)
	// oauth2client.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	oauth2client.UpdateDefaultUpdateTime = oauth2clientDescUpdateTime.UpdateDefault.(func() time.Time)
	// oauth2clientDescInternalID is the schema descriptor for internal_id field.
	oauth2clientDescInternalID := oauth2clientFields[0].Descriptor()
	// oauth2client.DefaultInternalID holds the default value on creation for the internal_id field.
	oauth2client.DefaultInternalID = oauth2clientDescInternalID.Default.(func() uuid.UUID)
	// oauth2clientDescSecret is the schema descriptor for secret field.
	oauth2clientDescSecret := oauth2clientFields[1].Descriptor()
	// oauth2client.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	oauth2client.SecretValidator = func() func(string) error {
		validators := oauth2clientDescSecret.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(secret string) error {
			for _, fn := range fns {
				if err := fn(secret); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// oauth2clientDescName is the schema descriptor for name field.
	oauth2clientDescName := oauth2clientFields[5].Descriptor()
	// oauth2client.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauth2client.NameValidator = oauth2clientDescName.Validators[0].(func(string) error)
}
