// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthCode is the predicate function for authcode builders.
type AuthCode func(*sql.Selector)

// AuthRequest is the predicate function for authrequest builders.
type AuthRequest func(*sql.Selector)

// OAuth2Client is the predicate function for oauth2client builders.
type OAuth2Client func(*sql.Selector)
